app = "odoo-bibliotheque"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8069"

[http_service]
  internal_port = 8069
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "odoo_data"
  destination = "/var/lib/odoo"
